### ISSUE TITLE
overlapped or disjoint?

### ISSUE THREAD

**Issue by EDGSCOUT** [fcdl94/FSS#12]
if task.disjoint:      # disjoint or overlapped ?
                for cl, img_set in self.full_data.class_to_images.items():
                    if cl not in self.labels and (cl != 0):
                        idxs = idxs.difference(img_set)

I think it is the overlapped setting, not disjoint?
Is it?

**Comment by fcdl94** [comment]
hello,

this is disjoint since it removes all the image that contains at least one class that is not seen (then future class).
