### ISSUE TITLE
Where is the implementation of Eqn.3 in the code?

### ISSUE THREAD

**Issue by Pixie8888** [fcdl94/FSS#15]
Hi,

Thanks for releasing the code. I have a question in the method "PIFS". In the incremental stage, the classifier of the new classes are initialized via feature prototype (Eqn.3 in the paper). But I didn't find this implementation in the code corresponding to "PIFS". 

Based on my understanding, the method of "PIFS" use the Trainer in the methods/trainer.py as the model. But the Trainer didn't provide the implementation of Eqn.3. 

Could you please help me pointing out the implementation of Eqn.3 for PIFS? Thank you!

**Comment by fcdl94** [comment]
Hi, 

Since PIFS has the Trainer class WI, the imprinting is performed in https://github.com/fcdl94/FSS/blob/6910c6864761526a35ba0cb0e1bcabed01ce86dc/methods/imprinting.py#L123

**Comment by Pixie8888** [comment]
Thanks.
