### ISSUE TITLE
Obtained Much Higher mIoU-N in VOC

### ISSUE THREAD

**Issue by justsosoha** [fcdl94/FSS#16]
I followed the instructions to obtain a result of 5-0m on the VOC dataset using task: 5-0, but I achieved a much higher metric of 0.214, which is much higher than the 0.133 in the supplementary materials. I obtained the final indicator by taking the mean of 15 data points. Could you please tell me if this process is correct？
![img1](https://github.com/fcdl94/FSS/assets/45748455/2ee218b5-6fb3-46e0-9006-83dd5c5cbb5b)
![img2](https://github.com/fcdl94/FSS/assets/45748455/9d3ebe07-4d4c-470c-a961-0cead6972ae7)

**Comment by fcdl94** [comment]
Hey! Actually, the reported mean is the mean of three data points, the ones at the last step (5). In your case 0.143, 0.101, 0.134, which actually is 12.6% (close enough to be acceptable)

**Comment by justsosoha** [comment]
> Hey! Actually, the reported mean is the mean of three data points, the ones at the last step (5). In your case 0.143, 0.101, 0.134, which actually is 12.6% (close enough to be acceptable)

I understand. Thanks! And thanks for your excellent work.
