### ISSUE TITLE
How to run the code

### ISSUE THREAD

**Issue by HieuPhan33** [fcdl94/FSS#2]
Hi,
thanks for sharing the source code.
Could you please show me how to run the code (with recommeded parameters) to reproduce the result?

There are several bash scripts: run.sh, run_1.sh, voc.sh, coco.sh.
Which one should I use to reproduce the result?

Thanks for your help.

**Comment by fcdl94** [comment]
Hi! Thanks for your interest! 

I've updated the repo. Now you can find the instruction and the scripts to run it!
