### ISSUE TITLE
AssertionError: a novel class has no pixels - Label id mismatch

### ISSUE THREAD

**Issue by HieuPhan33** [fcdl94/FSS#3]
Hi, 
I execute the bash script `run.py` for task `7mc` on `coco` dataset.

When training on step 1 with `ns=2`, I get ​an assertion error on line 176 in `methods/imprinting.py`: `AssertionError: Error, a novel class has no pixels`.

Here are some of my inspections:
1) In `imprinting.py` script, the `new_classes` is `[74]` which corresponds to the total number of classes in the previous step; 
2) However, the unique labels in the sample are `[18, 19, 255]` for `is=2`, [19, 255] for `is=3`. In other words, we only select image with label 19 on `coco-7mc-step1`;
3) In `task.py`, the actual new class id is 21;

So I doubt that the issue could be the way we filter images by labels in `dataset/dataset.py`.

I would appreciate if you provide some help. Thank you in advance.

**Comment by fcdl94** [comment]
Hi! Can you please check the instructions that I've posted today?
I think they will solve the issue! Sorry if I uploaded them late!

**Comment by HieuPhan33** [comment]
Hi, yes the label mismatch is solved. Thanks.
