### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'pixel_imprinting'

### ISSUE THREAD

**Issue by HieuPhan33** [fcdl94/FSS#4]
Hi,
When I train WI on step 1 with the following command:
`python -m torch.distributed.launch --master_port 6006 --nproc_per_node=1 run.py --method WI --name WIT --iter $2000 --lr 0.0001 --task 20-0 --dataset coco --ishot 3 --input_mix novel --val_interval 1000 --ckpt_interval 5 --step 1 --nshot 5 --step_ckpt ${path}/COS_0.pth`

I have the following error: `NameSpace object has no attribute pixel_imprinting` on line 70 in methods/imprinting.py

**Comment by fcdl94** [comment]
Ups, sorry, I should have forgotten to remove it while cleaning. I'll fix it. Thanks!

**Comment by HieuPhan33** [comment]
Hi, thanks for your fix. I see that there is still `self.pixel` variable being used on line 108 in imprinting.py

I still have the error: ` 'WeightImprinting' object has no attribute 'pixel'`. Could you please double check?
