### ISSUE TITLE
Which COCO/VOC settings are used in the paper

### ISSUE THREAD

**Issue by HieuPhan33** [fcdl94/FSS#5]
Hi, the paper considers 15 and 60 of base classes, and 5 and 20 of new classes for VOC and COCO, respectively.
However, there are many settings VOC (15-5, 5-0, etc.) or COCO (20-0, 20-1, etc.) have 15-5 and 60-20 base and new classes.

Could you please tell me which VOC/COCO setting did you use in the paper?
And if possible, the id of `ishot` for such results.

**Comment by fcdl94** [comment]
Hi @HieuPhan33.
Sure, for VOC I used:
5-0, 5-1, 5-2, 5-3 (with the "5-*m" version for the multi step)
For COCO I used:
20-0, 20-1, 20-2, 20-3 (again, with "m" for the multi step)

The shot are 0, 1, and 2.

You can find the scripts in the `run` folder

**Comment by HieuPhan33** [comment]
Hi, thanks for your response.

Can I assume that the reported result for one setting (e.g., single-scale 1 shot) is the average of all variants (e.g, 5-0, 5-1, 5-2, 5-3) and all sampling index (e.g. ishot=0,1,2,3,4,5) which are 20 combinations in total?

**Comment by fcdl94** [comment]
It is the average of 5-0, 5-1, 5-2, 5-3 using ishot=0,1,2 (leading to 12 combinations)
