### ISSUE TITLE
Different weight imprinting result in table 2 and table 3 and unable to run evaluation script

### ISSUE THREAD

**Issue by RogerQi** [fcdl94/FSS#7]
Hello,

First of all - thanks for open-sourcing the great work!

I have a question about the WI (weight imprinting) result of COCO-SS in table 2 and COCO-MS in table 3. Aren't they supposed to be close? As I understand how WI works - WI does not change feature extractor and new classifier weights are appended to the classifier weights using masked averaged pooling on provided samples. Therefore, if the samples provided to the model are the same, WI result should be consistent whether or not the setting is single-step (SS) or multi-step (MS). However, for instance, in table 2, the WI method gets 8.7 novel IoU in 5-shot case. However in table 3, the WI method gets 10.3 novel IoU in 5-shot case, which seems to be a significant improvement than table 2.

What are the factors here that cause the performance difference? Is it because of randomness of samples or is there some other factor that I did not consider?

I tried to run ./run/coco-ms.sh to understand what is happening. I use task 20-1m as an example. I did base stage training on COS and commented out all experiments except the WI one. But I got the following exception - it seems to have something to do with the class_to_img_id mapping but I followed the instruction exactly to prepare the dataset.

```
➜  FSS git:(master) ✗ ./run/coco-ms.sh
2365
2021-12-16 05:11:16.975790: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Device: cuda:0
Dataset: coco, Train set: 5, Val set: 5000
Total batch size is 5
Train loader contains 1 iterations per epoch, multiplied by 20
Total iterations are 1, corresponding to 0 epochs
Backbone: resnet101
[!] Model made with pre-trained
[!] Previous model loaded from checkpoints/step/20-1m-coco/COS_0.pth
Warm up lap!
[!] Train from the beginning of the task
tensor([[61]])
Cooling down...
[!] Checkpoint saved.
*** Test the model on all seen classes...
Dataset: coco, Test set: 5000
*** Model restored from checkpoints/step/20-1m-coco/WI-s1-i0_1.pth
Validation, Class Loss=0.6551916599273682
Done test on all
*** End of Test on all, Total Loss=0.6551916599273682

Total samples: 5000.000000
Overall Acc: 0.635754
Mean Acc: 0.481951
Mean Precision: 0.280138
FreqW Acc: 0.486665
Mean IoU: 0.276608
Class IoU:
	B: 0.2638237064899347
	N: 0.045324342936183426
Class Acc:
	B: 0.460117586250249
	N: 0.07358551581904954
Class Prec:
	B: 0.2946033495916806
	N: 0.1036611978337707

Closing the Logger.
2021-12-16 05:15:15.699890: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Device: cuda:0
Dataset: coco, Train set: 5, Val set: 5000
Total batch size is 5
Train loader contains 1 iterations per epoch, multiplied by 20
Total iterations are 1, corresponding to 0 epochs
Backbone: resnet101
[!] Model made with pre-trained
[!] Previous model loaded from checkpoints/step/20-1m-coco/WI-s1-i0_1.pth
Warm up lap!
Traceback (most recent call last):
  File "run.py", line 301, in <module>
    main(opts)
  File "run.py", line 157, in main
    model.warm_up(train_dst_no_aug)
  File "/home/roger/reproduction/FSS/methods/trainer.py", line 177, in warm_up
    self.warm_up_(dataset, epochs)
  File "/home/roger/reproduction/FSS/methods/imprinting.py", line 113, in warm_up_
    assert torch.any(count != 0), "Error, a novel class has no pixels!"
AssertionError: Error, a novel class has no pixels!
Killing subprocess 168145
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'run.py', '--local_rank=0', '--num_workers', '4', '--dataset', 'coco', '--task', '20-1m', '--method', 'WI', '--name', 'WI', '--iter', '0', '--lr', '0.001', '--ishot', '0', '--input_mix', 'novel', '--val_interval', '1000', '--ckpt_interval', '5', '--no_pooling', '--step', '2', '--nshot', '1']' returned non-zero exit status 1.

```

**Comment by fcdl94** [comment]
Hi @RogerQi!

Yes, WI gets the same results in the last step of the multi-step and in the single step. However, you may notice that the results reported in Table 3 are averaged across steps, so they are not the ones at the last step (which, I checked on my partial results, are actually equal to the single-step except for a very small variance).

For the code error, I will run some experiments on my workstation and I will let you know. Thanks!

**Comment by fcdl94** [comment]
Can you run the experiment on Pascal-VOC? I would understand if the error is related to the dataset or something else. 
Have you run `data/coco/make_annotation.py`?

**Comment by RogerQi** [comment]
Hello @fcdl94! Thanks for the clarification. I double-checked and it seemed that the data I used was corrupted and some of the PNG files are malformed. Deleting everything and following the provided README.md solves the problem.
