### ISSUE TITLE
Supplementary materials

### ISSUE THREAD

**Issue by RogerQi** [fcdl94/FSS#8]
In the paper posted on arxiv, it seems that many details are omitted due to space limitations and are reported in the supplementary materials. I was wondering if it is possible to share the supplementary materials here? They would be very useful for reproduction purpose.

**Comment by fcdl94** [comment]
I assumed they were accessible by BMVC webpage :) Sorry. 

[supp.pdf](https://github.com/fcdl94/FSS/files/7733989/supp.pdf)

**Comment by RogerQi** [comment]
Thanks! I really appreciate it. As a final comment before I close the issue - IMO adding this pdf to the README will help people who are looking for supplementarys.

**Comment by fcdl94** [comment]
Thanks, I'll do it :)
